apiVersion: v2
name: app-service
description: Simple tasks API with PostgreSQL backend
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - api
  - nodejs
  - postgresql
maintainers:
  - name: Tutorial Helmfile